/**
 * Control Unit Engine
 * Decodes 4-bit opcodes into physical micro-architectural control signals.
 */

export interface ControlSignals {
  regWrite: boolean;
  memRead: boolean;
  memWrite: boolean;
  aluSrc: boolean; // 0 = RegB, 1 = Immediate
  aluOp: number;   // 3-bit ALU opcode (0=ADD, 1=SUB, 2=AND, 3=OR, 4=XOR, 5=NOT, 6=SHL, 7=SHR)
  aluOpName: string;
  branch: boolean;
  branchCondition: 'NONE' | 'BEQ' | 'BNE';
  jump: boolean;
  memToReg: boolean; // 0 = ALU, 1 = MEM
  halt: boolean;
  description: string;
}

export interface InstructionDef {
  opcode: number;
  mnemonic: string;
  type: 'R' | 'I' | 'J';
  syntax: string;
  description: string;
  signals: ControlSignals;
}

export const INSTRUCTION_SET: InstructionDef[] = [
  {
    opcode: 0,
    mnemonic: 'NOP',
    type: 'J',
    syntax: 'NOP',
    description: 'No Operation',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'Advances to the next cycle without modifying registers or memory.',
    },
  },
  {
    opcode: 1,
    mnemonic: 'ADD',
    type: 'R',
    syntax: 'ADD Rd, Rs, Rt',
    description: 'Addition: Rd = Rs + Rt',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU computes Rs + Rt. The result is written into destination register Rd.',
    },
  },
  {
    opcode: 2,
    mnemonic: 'SUB',
    type: 'R',
    syntax: 'SUB Rd, Rs, Rt',
    description: 'Subtraction: Rd = Rs - Rt',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 1,
      aluOpName: 'SUB',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU computes Rs - Rt. The result is written into destination register Rd.',
    },
  },
  {
    opcode: 3,
    mnemonic: 'AND',
    type: 'R',
    syntax: 'AND Rd, Rs, Rt',
    description: 'Bitwise AND: Rd = Rs & Rt',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 2,
      aluOpName: 'AND',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU performs a bitwise AND between Rs and Rt.',
    },
  },
  {
    opcode: 4,
    mnemonic: 'OR',
    type: 'R',
    syntax: 'OR Rd, Rs, Rt',
    description: 'Bitwise OR: Rd = Rs | Rt',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 3,
      aluOpName: 'OR',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU performs a bitwise OR between Rs and Rt.',
    },
  },
  {
    opcode: 5,
    mnemonic: 'XOR',
    type: 'R',
    syntax: 'XOR Rd, Rs, Rt',
    description: 'Bitwise XOR: Rd = Rs ^ Rt',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 4,
      aluOpName: 'XOR',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU performs a bitwise XOR between Rs and Rt.',
    },
  },
  {
    opcode: 6,
    mnemonic: 'NOT',
    type: 'R',
    syntax: 'NOT Rd, Rs',
    description: 'Bitwise NOT: Rd = ~Rs',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 5,
      aluOpName: 'NOT',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU inverts all bits of Rs and writes the result into Rd.',
    },
  },
  {
    opcode: 7,
    mnemonic: 'ADDI',
    type: 'I',
    syntax: 'ADDI Rd, Rs, imm',
    description: 'Add Immediate: Rd = Rs + imm',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: true,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALUSrc selects the immediate operand for ALU Input B. Writes Rs + imm into Rd.',
    },
  },
  {
    opcode: 8,
    mnemonic: 'LOAD',
    type: 'I',
    syntax: 'LOAD Rd, [addr]',
    description: 'Memory Read: Rd = MEM[addr]',
    signals: {
      regWrite: true,
      memRead: true,
      memWrite: false,
      aluSrc: true,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: true,
      halt: false,
      description: 'Reads data from RAM at target address and writes it into destination register Rd.',
    },
  },
  {
    opcode: 9,
    mnemonic: 'STORE',
    type: 'I',
    syntax: 'STORE Rs, [addr]',
    description: 'Memory Write: MEM[addr] = Rs',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: true,
      aluSrc: true,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'Writes the contents of register Rs into RAM at target address.',
    },
  },
  {
    opcode: 10,
    mnemonic: 'BEQ',
    type: 'I',
    syntax: 'BEQ Rs, Rt, target',
    description: 'Branch if Equal: if (Rs == Rt) PC = target',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 1,
      aluOpName: 'SUB',
      branch: true,
      branchCondition: 'BEQ',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU computes Rs - Rt. If Zero flag (Z=1), the PC multiplexer loads the branch target.',
    },
  },
  {
    opcode: 11,
    mnemonic: 'BNE',
    type: 'I',
    syntax: 'BNE Rs, Rt, target',
    description: 'Branch if Not Equal: if (Rs != Rt) PC = target',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 1,
      aluOpName: 'SUB',
      branch: true,
      branchCondition: 'BNE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'ALU computes Rs - Rt. If Zero flag is cleared (Z=0), the PC multiplexer loads the branch target.',
    },
  },
  {
    opcode: 12,
    mnemonic: 'JMP',
    type: 'J',
    syntax: 'JMP target',
    description: 'Unconditional Jump: PC = target',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: true,
      memToReg: false,
      halt: false,
      description: 'The Jump control signal forces the Program Counter to load the target destination address immediately.',
    },
  },
  {
    opcode: 13,
    mnemonic: 'SHL',
    type: 'R',
    syntax: 'SHL Rd, Rs',
    description: 'Logical Shift Left: Rd = Rs << 1',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 6,
      aluOpName: 'SHL',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'Performs a logical shift left by 1 bit on Rs and stores result in Rd.',
    },
  },
  {
    opcode: 14,
    mnemonic: 'SHR',
    type: 'R',
    syntax: 'SHR Rd, Rs',
    description: 'Logical Shift Right: Rd = Rs >> 1',
    signals: {
      regWrite: true,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 7,
      aluOpName: 'SHR',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: false,
      description: 'Performs a logical shift right by 1 bit on Rs and stores result in Rd.',
    },
  },
  {
    opcode: 15,
    mnemonic: 'HALT',
    type: 'J',
    syntax: 'HALT',
    description: 'Halt Processor Execution',
    signals: {
      regWrite: false,
      memRead: false,
      memWrite: false,
      aluSrc: false,
      aluOp: 0,
      aluOpName: 'ADD',
      branch: false,
      branchCondition: 'NONE',
      jump: false,
      memToReg: false,
      halt: true,
      description: 'Stops processor clocking and terminates program execution.',
    },
  },
];

export function decodeInstruction(opcode: number): InstructionDef {
  const op = INSTRUCTION_SET.find(inst => inst.opcode === (opcode & 0x0F));
  return op || INSTRUCTION_SET[0];
}
