/**
 * Intel 8086 Instruction Reference Database
 * Searchable catalog with operands, encodings, flags, T-states, and examples.
 */

export type InstructionCategory =
  | 'Data Transfer'
  | 'Arithmetic'
  | 'Logic'
  | 'Shift & Rotate'
  | 'Control Transfer'
  | 'String'
  | 'Stack'
  | 'Processor Control'
  | 'BCD';

export interface InstructionEntry {
  mnemonic: string;
  category: InstructionCategory;
  syntax: string[];
  description: string;
  operands: string;
  opcodeBytes: string;
  instructionSize: string;
  flagsAffected: string[];
  flagsCleared: string[];
  clocksMin: number;
  clocksMax: number;
  example: {
    before: string;
    instruction: string;
    after: string;
    machineCode: string;
  };
}

export const INSTRUCTION_DATABASE: InstructionEntry[] = [
  // ── Data Transfer ─────────────────────────────────────────────────────────
  {
    mnemonic: 'MOV',
    category: 'Data Transfer',
    syntax: ['MOV dst, src'],
    description: 'Copies the source operand into the destination. The source is not modified. Flags are not affected.',
    operands: 'reg/mem ← reg/mem/imm (byte or word)',
    opcodeBytes: 'B8+r (reg, imm16), 89 /r (reg, reg16), 8B /r (reg, mem)',
    instructionSize: '2–6 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 9,
    example: {
      before: 'AX = 0000H',
      instruction: 'MOV AX, 1234H',
      after: 'AX = 1234H',
      machineCode: 'B8 34 12',
    },
  },
  {
    mnemonic: 'XCHG',
    category: 'Data Transfer',
    syntax: ['XCHG dst, src'],
    description: 'Swaps the contents of the two operands. No flags are affected.',
    operands: 'reg16 ↔ reg16 or reg8 ↔ reg8',
    opcodeBytes: '90+r (AX,reg16), 87 /r (reg16,reg16), 86 /r (reg8,reg8)',
    instructionSize: '1–2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 1234H, BX = 5678H',
      instruction: 'XCHG AX, BX',
      after: 'AX = 5678H, BX = 1234H',
      machineCode: '87 C3',
    },
  },
  {
    mnemonic: 'PUSH',
    category: 'Stack',
    syntax: ['PUSH src'],
    description: 'Decrements SP by 2, then stores the 16-bit source operand at SS:SP.',
    operands: 'reg16 / mem16 / seg',
    opcodeBytes: '50+r (reg16), FF /6 (mem16)',
    instructionSize: '1–2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 10,
    clocksMax: 10,
    example: {
      before: 'AX = 1234H, SP = 0100H',
      instruction: 'PUSH AX',
      after: 'SS:[00FEH] = 1234H, SP = 00FEH',
      machineCode: '50',
    },
  },
  {
    mnemonic: 'POP',
    category: 'Stack',
    syntax: ['POP dst'],
    description: 'Loads the 16-bit word at SS:SP into the destination, then increments SP by 2.',
    operands: 'reg16 / mem16 / seg',
    opcodeBytes: '58+r (reg16), 8F /0 (mem16)',
    instructionSize: '1–2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 8,
    clocksMax: 8,
    example: {
      before: 'SS:[00FEH] = 1234H, SP = 00FEH',
      instruction: 'POP AX',
      after: 'AX = 1234H, SP = 0100H',
      machineCode: '58',
    },
  },
  {
    mnemonic: 'PUSHF',
    category: 'Stack',
    syntax: ['PUSHF'],
    description: 'Pushes the FLAGS register onto the stack. SP is decremented by 2.',
    operands: '(none)',
    opcodeBytes: '9C',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 10,
    clocksMax: 10,
    example: {
      before: 'FLAGS = 0246H, SP = 0100H',
      instruction: 'PUSHF',
      after: 'SS:[00FEH] = 0246H, SP = 00FEH',
      machineCode: '9C',
    },
  },
  {
    mnemonic: 'POPF',
    category: 'Stack',
    syntax: ['POPF'],
    description: 'Pops the top of the stack into the FLAGS register. SP is incremented by 2.',
    operands: '(none)',
    opcodeBytes: '9D',
    instructionSize: '1 byte',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'TF', 'IF', 'DF', 'OF'],
    flagsCleared: [],
    clocksMin: 8,
    clocksMax: 8,
    example: {
      before: 'SS:[00FEH] = 0247H, SP = 00FEH',
      instruction: 'POPF',
      after: 'FLAGS = 0247H, SP = 0100H',
      machineCode: '9D',
    },
  },
  // ── Arithmetic ─────────────────────────────────────────────────────────────
  {
    mnemonic: 'ADD',
    category: 'Arithmetic',
    syntax: ['ADD dst, src'],
    description: 'Adds the source to the destination and stores the result in the destination. Updates all status flags.',
    operands: 'reg/mem ← reg/mem/imm (byte or word)',
    opcodeBytes: '01 /r (reg16+reg16), 03 /r (reg16+mem16), 05 iw (AX+imm16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0003H, BX = 0005H',
      instruction: 'ADD AX, BX',
      after: 'AX = 0008H, CF=0, ZF=0, SF=0, OF=0',
      machineCode: '01 D8',
    },
  },
  {
    mnemonic: 'ADC',
    category: 'Arithmetic',
    syntax: ['ADC dst, src'],
    description: 'Adds source, destination, and the Carry Flag (CF). Useful for multi-word precision additions.',
    operands: 'reg/mem ← reg/mem/imm + CF',
    opcodeBytes: '11 /r (reg16+reg16+CF)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0001H, BX = 0001H, CF=1',
      instruction: 'ADC AX, BX',
      after: 'AX = 0003H (1+1+CF=3)',
      machineCode: '11 D8',
    },
  },
  {
    mnemonic: 'SUB',
    category: 'Arithmetic',
    syntax: ['SUB dst, src'],
    description: 'Subtracts source from destination and stores the result in destination. Updates all status flags.',
    operands: 'reg/mem ← reg/mem − reg/mem/imm',
    opcodeBytes: '29 /r (reg16-reg16), 81 /5 iw (reg16-imm16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0009H, BX = 0004H',
      instruction: 'SUB AX, BX',
      after: 'AX = 0005H, CF=0, ZF=0',
      machineCode: '29 D8',
    },
  },
  {
    mnemonic: 'SBB',
    category: 'Arithmetic',
    syntax: ['SBB dst, src'],
    description: 'Subtracts source and the Carry Flag from the destination. Used in multi-word precision subtraction.',
    operands: 'reg/mem ← reg/mem − reg/mem/imm − CF',
    opcodeBytes: '19 /r (reg16-reg16-CF)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0005H, BX = 0002H, CF=1',
      instruction: 'SBB AX, BX',
      after: 'AX = 0002H (5-2-CF=2)',
      machineCode: '19 D8',
    },
  },
  {
    mnemonic: 'INC',
    category: 'Arithmetic',
    syntax: ['INC dst'],
    description: 'Increments the destination by 1. CF is not affected. All other arithmetic flags are set.',
    operands: 'reg/mem ← reg/mem + 1',
    opcodeBytes: '40+r (reg16), FE /0 (reg8), FF /0 (mem16)',
    instructionSize: '1–2 bytes',
    flagsAffected: ['PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 3,
    example: {
      before: 'CX = 0004H',
      instruction: 'INC CX',
      after: 'CX = 0005H (CF unchanged)',
      machineCode: '41',
    },
  },
  {
    mnemonic: 'DEC',
    category: 'Arithmetic',
    syntax: ['DEC dst'],
    description: 'Decrements the destination by 1. CF is not affected. All other arithmetic flags are set.',
    operands: 'reg/mem ← reg/mem − 1',
    opcodeBytes: '48+r (reg16), FE /1 (reg8), FF /1 (mem16)',
    instructionSize: '1–2 bytes',
    flagsAffected: ['PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 3,
    example: {
      before: 'CX = 0005H',
      instruction: 'DEC CX',
      after: 'CX = 0004H (CF unchanged)',
      machineCode: '49',
    },
  },
  {
    mnemonic: 'NEG',
    category: 'Arithmetic',
    syntax: ['NEG dst'],
    description: 'Replaces the destination with its two\'s complement negation (0 − dst). CF=1 if operand is non-zero.',
    operands: 'reg/mem ← 0 − reg/mem',
    opcodeBytes: 'F7 /3 (reg16), F6 /3 (reg8)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 3,
    example: {
      before: 'AX = 0005H',
      instruction: 'NEG AX',
      after: 'AX = FFFBH (-5 in 2\'s complement), CF=1',
      machineCode: 'F7 D8',
    },
  },
  {
    mnemonic: 'CMP',
    category: 'Arithmetic',
    syntax: ['CMP dst, src'],
    description: 'Compares src and dst by computing dst − src. The result is discarded; only flags are updated. Used before conditional jumps.',
    operands: 'Sets flags based on dst − src (result not stored)',
    opcodeBytes: '39 /r (reg16-reg16), 3D iw (AX-imm16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 3,
    example: {
      before: 'AX = 000AH, BX = 000AH',
      instruction: 'CMP AX, BX',
      after: 'ZF=1 (equal), CF=0, OF=0',
      machineCode: '39 D8',
    },
  },
  {
    mnemonic: 'MUL',
    category: 'Arithmetic',
    syntax: ['MUL src'],
    description: 'Unsigned multiply: AX ← AL × src8 (8-bit) or DX:AX ← AX × src16 (16-bit).',
    operands: 'AL/AX (implicit) × reg/mem → AX or DX:AX',
    opcodeBytes: 'F7 /4 (reg16), F6 /4 (reg8)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 70,
    clocksMax: 77,
    example: {
      before: 'AX = 0004H, BX = 0005H',
      instruction: 'MUL BX',
      after: 'DX:AX = 00000014H (4×5=20)',
      machineCode: 'F7 E3',
    },
  },
  {
    mnemonic: 'IMUL',
    category: 'Arithmetic',
    syntax: ['IMUL src'],
    description: 'Signed multiply: Same as MUL but treats operands as signed two\'s complement values.',
    operands: 'AL/AX (implicit, signed) × reg/mem → AX or DX:AX',
    opcodeBytes: 'F7 /5 (reg16), F6 /5 (reg8)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 80,
    clocksMax: 98,
    example: {
      before: 'AX = FFFEH (-2), BX = 0005H',
      instruction: 'IMUL BX',
      after: 'DX:AX = FFFFFFF6H (-10 signed)',
      machineCode: 'F7 EB',
    },
  },
  {
    mnemonic: 'DIV',
    category: 'Arithmetic',
    syntax: ['DIV src'],
    description: 'Unsigned divide: AX ÷ src8 → AL (quotient), AH (remainder). Or DX:AX ÷ src16 → AX (quotient), DX (remainder).',
    operands: 'AX/DX:AX (implicit) ÷ reg/mem → quotient, remainder',
    opcodeBytes: 'F7 /6 (reg16), F6 /6 (reg8)',
    instructionSize: '2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 80,
    clocksMax: 90,
    example: {
      before: 'AX = 000BH (11), BL = 03H (3)',
      instruction: 'DIV BL',
      after: 'AL = 03H (quotient), AH = 02H (remainder)',
      machineCode: 'F6 F3',
    },
  },
  {
    mnemonic: 'DAA',
    category: 'BCD',
    syntax: ['DAA'],
    description: 'Decimal Adjust AL after Addition. Corrects AL after BCD addition so it contains a valid packed BCD digit.',
    operands: 'AL ← BCD-adjusted AL',
    opcodeBytes: '27',
    instructionSize: '1 byte',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF'],
    flagsCleared: [],
    clocksMin: 4,
    clocksMax: 4,
    example: {
      before: 'AL = 38H (BCD 38) + BL = 47H (BCD 47) → AL = 7FH',
      instruction: 'DAA (immediately after ADD AL, BL)',
      after: 'AL = 85H (BCD 85)',
      machineCode: '27',
    },
  },
  {
    mnemonic: 'DAS',
    category: 'BCD',
    syntax: ['DAS'],
    description: 'Decimal Adjust AL after Subtraction. Corrects AL after BCD subtraction.',
    operands: 'AL ← BCD-adjusted AL',
    opcodeBytes: '2F',
    instructionSize: '1 byte',
    flagsAffected: ['CF', 'PF', 'AF', 'ZF', 'SF'],
    flagsCleared: [],
    clocksMin: 4,
    clocksMax: 4,
    example: {
      before: 'AL = 85H after BCD subtract',
      instruction: 'DAS',
      after: 'AL = corrected BCD result',
      machineCode: '2F',
    },
  },
  {
    mnemonic: 'CBW',
    category: 'Arithmetic',
    syntax: ['CBW'],
    description: 'Convert Byte to Word. Sign-extends the byte in AL into AX (AH gets the sign bit of AL).',
    operands: 'AX ← Sign-extended AL',
    opcodeBytes: '98',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'AL = F0H (-16 signed)',
      instruction: 'CBW',
      after: 'AX = FFF0H (-16 word)',
      machineCode: '98',
    },
  },
  {
    mnemonic: 'CWD',
    category: 'Arithmetic',
    syntax: ['CWD'],
    description: 'Convert Word to Doubleword. Sign-extends AX into DX:AX (DX gets the sign bit of AX).',
    operands: 'DX:AX ← Sign-extended AX',
    opcodeBytes: '99',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 5,
    clocksMax: 5,
    example: {
      before: 'AX = 8000H (-32768 signed)',
      instruction: 'CWD',
      after: 'DX = FFFFH, AX = 8000H (DX:AX = -32768)',
      machineCode: '99',
    },
  },
  // ── Logic ──────────────────────────────────────────────────────────────────
  {
    mnemonic: 'AND',
    category: 'Logic',
    syntax: ['AND dst, src'],
    description: 'Bitwise logical AND. Each bit of the result is 1 only if the corresponding bits in both operands are 1. CF and OF are cleared.',
    operands: 'reg/mem ← reg/mem AND reg/mem/imm',
    opcodeBytes: '21 /r (reg16 AND reg16), 81 /4 iw (reg16 AND imm16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['PF', 'ZF', 'SF'],
    flagsCleared: ['CF', 'OF'],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0F0FH, BX = 00FFH',
      instruction: 'AND AX, BX',
      after: 'AX = 000FH, CF=0, OF=0',
      machineCode: '21 D8',
    },
  },
  {
    mnemonic: 'OR',
    category: 'Logic',
    syntax: ['OR dst, src'],
    description: 'Bitwise logical OR. Each bit of the result is 1 if either corresponding bit is 1. CF and OF are cleared.',
    operands: 'reg/mem ← reg/mem OR reg/mem/imm',
    opcodeBytes: '09 /r (reg16 OR reg16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['PF', 'ZF', 'SF'],
    flagsCleared: ['CF', 'OF'],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 0F00H, BX = 000FH',
      instruction: 'OR AX, BX',
      after: 'AX = 0F0FH, CF=0, OF=0',
      machineCode: '09 D8',
    },
  },
  {
    mnemonic: 'XOR',
    category: 'Logic',
    syntax: ['XOR dst, src'],
    description: 'Bitwise exclusive OR. Each bit of the result is 1 only if the corresponding bits differ. XOR reg, reg is the standard way to zero a register.',
    operands: 'reg/mem ← reg/mem XOR reg/mem/imm',
    opcodeBytes: '31 /r (reg16 XOR reg16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['PF', 'ZF', 'SF'],
    flagsCleared: ['CF', 'OF'],
    clocksMin: 3,
    clocksMax: 17,
    example: {
      before: 'AX = 1234H',
      instruction: 'XOR AX, AX',
      after: 'AX = 0000H, ZF=1 (standard zero technique)',
      machineCode: '31 C0',
    },
  },
  {
    mnemonic: 'NOT',
    category: 'Logic',
    syntax: ['NOT dst'],
    description: 'Bitwise complement. Inverts every bit in the operand. No flags are affected.',
    operands: 'reg/mem ← ~reg/mem',
    opcodeBytes: 'F7 /2 (reg16), F6 /2 (reg8)',
    instructionSize: '2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 3,
    example: {
      before: 'AX = 5555H',
      instruction: 'NOT AX',
      after: 'AX = AAAAh (Flags unchanged)',
      machineCode: 'F7 D0',
    },
  },
  {
    mnemonic: 'TEST',
    category: 'Logic',
    syntax: ['TEST dst, src'],
    description: 'Non-destructive AND. Performs a bitwise AND and sets flags but does NOT store the result. Used to test specific bits.',
    operands: 'Sets flags based on dst AND src (result not stored)',
    opcodeBytes: '85 /r (reg16 AND reg16), F7 /0 iw (reg16 AND imm16)',
    instructionSize: '2–4 bytes',
    flagsAffected: ['PF', 'ZF', 'SF'],
    flagsCleared: ['CF', 'OF'],
    clocksMin: 3,
    clocksMax: 3,
    example: {
      before: 'AX = 0003H, BX = 0001H',
      instruction: 'TEST AX, BX',
      after: 'ZF=0 (bit 0 of AX is set), AX unchanged',
      machineCode: '85 C3',
    },
  },
  // ── Shift & Rotate ─────────────────────────────────────────────────────────
  {
    mnemonic: 'SHL / SAL',
    category: 'Shift & Rotate',
    syntax: ['SHL dst, 1', 'SHL dst, CL'],
    description: 'Logical / Arithmetic Shift Left. Each shift moves all bits one position to the left. The MSB is shifted into CF. The LSB is filled with 0.',
    operands: 'reg/mem ← reg/mem << count (1 or CL)',
    opcodeBytes: 'D1 /4 (reg16, count=1), D3 /4 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'PF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 0001H',
      instruction: 'SHL AX, 1',
      after: 'AX = 0002H, CF=0 (multiply by 2)',
      machineCode: 'D1 E0',
    },
  },
  {
    mnemonic: 'SHR',
    category: 'Shift & Rotate',
    syntax: ['SHR dst, 1', 'SHR dst, CL'],
    description: 'Logical Shift Right. Each shift moves all bits one position to the right. The LSB is shifted into CF. The MSB is filled with 0 (unsigned divide by 2).',
    operands: 'reg/mem ← reg/mem >> count (1 or CL, zero-fill MSB)',
    opcodeBytes: 'D1 /5 (reg16, count=1), D3 /5 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'PF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 0008H',
      instruction: 'SHR AX, 1',
      after: 'AX = 0004H (divide by 2, unsigned)',
      machineCode: 'D1 E8',
    },
  },
  {
    mnemonic: 'SAR',
    category: 'Shift & Rotate',
    syntax: ['SAR dst, 1', 'SAR dst, CL'],
    description: 'Arithmetic Shift Right. Each shift moves all bits one position to the right. The LSB is shifted into CF. The MSB retains its value (signed divide by 2).',
    operands: 'reg/mem ← reg/mem >> count (1 or CL, sign-fill MSB)',
    opcodeBytes: 'D1 /7 (reg16, count=1), D3 /7 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'PF', 'ZF', 'SF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 8000H (-32768 signed)',
      instruction: 'SAR AX, 1',
      after: 'AX = C000H (-16384, sign preserved)',
      machineCode: 'D1 F8',
    },
  },
  {
    mnemonic: 'ROL',
    category: 'Shift & Rotate',
    syntax: ['ROL dst, 1', 'ROL dst, CL'],
    description: 'Rotate Left. The MSB is shifted into both CF and the LSB, wrapping the bit around.',
    operands: 'reg/mem ← rotate left (MSB → CF and LSB)',
    opcodeBytes: 'D1 /0 (reg16, count=1), D3 /0 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 8001H',
      instruction: 'ROL AX, 1',
      after: 'AX = 0003H, CF=1 (MSB wrapped to LSB)',
      machineCode: 'D1 C0',
    },
  },
  {
    mnemonic: 'ROR',
    category: 'Shift & Rotate',
    syntax: ['ROR dst, 1', 'ROR dst, CL'],
    description: 'Rotate Right. The LSB is shifted into both CF and the MSB, wrapping the bit around.',
    operands: 'reg/mem ← rotate right (LSB → CF and MSB)',
    opcodeBytes: 'D1 /1 (reg16, count=1), D3 /1 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 0003H',
      instruction: 'ROR AX, 1',
      after: 'AX = 8001H, CF=1 (LSB wrapped to MSB)',
      machineCode: 'D1 C8',
    },
  },
  {
    mnemonic: 'RCL',
    category: 'Shift & Rotate',
    syntax: ['RCL dst, 1', 'RCL dst, CL'],
    description: 'Rotate Left through Carry. The CF bit is included in the rotation (17-bit ring for 16-bit operand).',
    operands: 'reg/mem ← rotate left through CF',
    opcodeBytes: 'D1 /2 (reg16, count=1), D3 /2 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 4000H, CF=1',
      instruction: 'RCL AX, 1',
      after: 'AX = 8001H, CF=0 (CF→LSB, MSB→CF)',
      machineCode: 'D1 D0',
    },
  },
  {
    mnemonic: 'RCR',
    category: 'Shift & Rotate',
    syntax: ['RCR dst, 1', 'RCR dst, CL'],
    description: 'Rotate Right through Carry. The CF bit is included in the rotation (17-bit ring for 16-bit operand).',
    operands: 'reg/mem ← rotate right through CF',
    opcodeBytes: 'D1 /3 (reg16, count=1), D3 /3 (reg16, count=CL)',
    instructionSize: '2 bytes',
    flagsAffected: ['CF', 'OF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 28,
    example: {
      before: 'AX = 0001H, CF=1',
      instruction: 'RCR AX, 1',
      after: 'AX = 8000H, CF=1 (CF→MSB, LSB→CF)',
      machineCode: 'D1 D8',
    },
  },
  // ── Control Transfer ────────────────────────────────────────────────────────
  {
    mnemonic: 'JMP',
    category: 'Control Transfer',
    syntax: ['JMP short label', 'JMP near label'],
    description: 'Unconditional jump. Transfers execution to the target address. Does not modify flags.',
    operands: 'IP ← target address',
    opcodeBytes: 'EB cb (short ±127 bytes), E9 cw (near ±32KB)',
    instructionSize: '2–3 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 15,
    clocksMax: 15,
    example: {
      before: 'IP = 0100H',
      instruction: 'JMP LOOP_START',
      after: 'IP = address of LOOP_START',
      machineCode: 'EB xx',
    },
  },
  {
    mnemonic: 'JE / JZ',
    category: 'Control Transfer',
    syntax: ['JE label', 'JZ label'],
    description: 'Jump if Equal / Zero. Jumps if ZF=1 (the previous CMP, SUB or arithmetic set ZF).',
    operands: 'IP ← target if ZF=1',
    opcodeBytes: '74 cb',
    instructionSize: '2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 4,
    clocksMax: 16,
    example: {
      before: 'CMP AX, BX → ZF=1 (AX==BX)',
      instruction: 'JE EQUAL_BRANCH',
      after: 'Jumps to EQUAL_BRANCH',
      machineCode: '74 xx',
    },
  },
  {
    mnemonic: 'JNE / JNZ',
    category: 'Control Transfer',
    syntax: ['JNE label', 'JNZ label'],
    description: 'Jump if Not Equal / Not Zero. Jumps if ZF=0.',
    operands: 'IP ← target if ZF=0',
    opcodeBytes: '75 cb',
    instructionSize: '2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 4,
    clocksMax: 16,
    example: {
      before: 'CX = 0005H (CX != 0)',
      instruction: 'JNZ LOOP_TOP',
      after: 'Jumps if CX was non-zero after DEC/CMP',
      machineCode: '75 xx',
    },
  },
  {
    mnemonic: 'LOOP',
    category: 'Control Transfer',
    syntax: ['LOOP label'],
    description: 'Decrements CX by 1, then jumps to label if CX ≠ 0. Used for definite-count loop control.',
    operands: 'CX ← CX−1; if CX≠0 then IP ← target',
    opcodeBytes: 'E2 cb',
    instructionSize: '2 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 5,
    clocksMax: 17,
    example: {
      before: 'CX = 0005H',
      instruction: 'LOOP LOOP_BODY',
      after: 'CX = 0004H, jumps 4 more times',
      machineCode: 'E2 xx',
    },
  },
  {
    mnemonic: 'CALL',
    category: 'Control Transfer',
    syntax: ['CALL near_proc'],
    description: 'Calls a procedure. Pushes the return address (IP of next instruction) onto the stack, then jumps to the procedure.',
    operands: 'PUSH IP; IP ← target',
    opcodeBytes: 'E8 cw (near call)',
    instructionSize: '3 bytes',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 19,
    clocksMax: 19,
    example: {
      before: 'SP = 0100H, IP = 0200H',
      instruction: 'CALL MY_PROC',
      after: 'SS:[00FEH] = 0203H, IP → MY_PROC',
      machineCode: 'E8 xx xx',
    },
  },
  {
    mnemonic: 'RET',
    category: 'Control Transfer',
    syntax: ['RET'],
    description: 'Returns from a near procedure. Pops the saved return address from the stack into IP.',
    operands: 'IP ← POP()',
    opcodeBytes: 'C3',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 8,
    clocksMax: 8,
    example: {
      before: 'SS:[00FEH] = 0203H, SP = 00FEH',
      instruction: 'RET',
      after: 'IP = 0203H, SP = 0100H',
      machineCode: 'C3',
    },
  },
  {
    mnemonic: 'INT',
    category: 'Control Transfer',
    syntax: ['INT n'],
    description: 'Software interrupt. Saves FLAGS, CS, and IP on the stack, then loads CS:IP from the interrupt vector table at address 4*n.',
    operands: 'INT 21H → DOS system call',
    opcodeBytes: 'CD ib',
    instructionSize: '2 bytes',
    flagsAffected: ['IF', 'TF'],
    flagsCleared: ['IF', 'TF'],
    clocksMin: 52,
    clocksMax: 52,
    example: {
      before: 'AH = 09H, DS:DX → "$"-terminated string',
      instruction: 'INT 21H',
      after: 'DOS displays the string on console',
      machineCode: 'CD 21',
    },
  },
  // ── String ─────────────────────────────────────────────────────────────────
  {
    mnemonic: 'MOVSB',
    category: 'String',
    syntax: ['MOVSB', 'REP MOVSB'],
    description: 'Moves a byte from DS:SI to ES:DI. SI and DI are incremented (DF=0) or decremented (DF=1) by 1. Used with REP for block moves.',
    operands: 'ES:[DI] ← DS:[SI]; SI,DI ← SI,DI ± 1',
    opcodeBytes: 'A4',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 18,
    clocksMax: 18,
    example: {
      before: 'DS:SI → source byte, ES:DI → dest',
      instruction: 'REP MOVSB (with CX = count)',
      after: 'CX bytes copied from DS:SI to ES:DI',
      machineCode: 'F3 A4',
    },
  },
  // ── Processor Control ──────────────────────────────────────────────────────
  {
    mnemonic: 'NOP',
    category: 'Processor Control',
    syntax: ['NOP'],
    description: 'No operation. Wastes 3 clock cycles. Often used for timing delays, code alignment, or as a placeholder.',
    operands: '(none)',
    opcodeBytes: '90',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 3,
    clocksMax: 3,
    example: {
      before: 'IP = 0100H',
      instruction: 'NOP',
      after: 'IP = 0101H (nothing else changes)',
      machineCode: '90',
    },
  },
  {
    mnemonic: 'HLT',
    category: 'Processor Control',
    syntax: ['HLT'],
    description: 'Halt. Stops instruction execution until an interrupt or reset occurs.',
    operands: '(none)',
    opcodeBytes: 'F4',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'Program running',
      instruction: 'HLT',
      after: 'Processor halted, waiting for interrupt',
      machineCode: 'F4',
    },
  },
  {
    mnemonic: 'CLC',
    category: 'Processor Control',
    syntax: ['CLC'],
    description: 'Clear Carry Flag. Sets CF = 0.',
    operands: 'CF ← 0',
    opcodeBytes: 'F8',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: ['CF'],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'CF = 1',
      instruction: 'CLC',
      after: 'CF = 0',
      machineCode: 'F8',
    },
  },
  {
    mnemonic: 'STC',
    category: 'Processor Control',
    syntax: ['STC'],
    description: 'Set Carry Flag. Sets CF = 1.',
    operands: 'CF ← 1',
    opcodeBytes: 'F9',
    instructionSize: '1 byte',
    flagsAffected: ['CF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'CF = 0',
      instruction: 'STC',
      after: 'CF = 1',
      machineCode: 'F9',
    },
  },
  {
    mnemonic: 'CLD',
    category: 'Processor Control',
    syntax: ['CLD'],
    description: 'Clear Direction Flag. Sets DF = 0. String operations (MOVSB, etc.) will auto-increment SI and DI.',
    operands: 'DF ← 0',
    opcodeBytes: 'FC',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: ['DF'],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'DF = 1',
      instruction: 'CLD',
      after: 'DF = 0 (MOVSB will increment SI, DI)',
      machineCode: 'FC',
    },
  },
  {
    mnemonic: 'STD',
    category: 'Processor Control',
    syntax: ['STD'],
    description: 'Set Direction Flag. Sets DF = 1. String operations will auto-decrement SI and DI.',
    operands: 'DF ← 1',
    opcodeBytes: 'FD',
    instructionSize: '1 byte',
    flagsAffected: ['DF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'DF = 0',
      instruction: 'STD',
      after: 'DF = 1 (MOVSB will decrement SI, DI)',
      machineCode: 'FD',
    },
  },
  {
    mnemonic: 'CLI',
    category: 'Processor Control',
    syntax: ['CLI'],
    description: 'Clear Interrupt Flag. Disables maskable hardware interrupts (IF = 0).',
    operands: 'IF ← 0',
    opcodeBytes: 'FA',
    instructionSize: '1 byte',
    flagsAffected: [],
    flagsCleared: ['IF'],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'IF = 1',
      instruction: 'CLI',
      after: 'IF = 0 (hardware interrupts masked)',
      machineCode: 'FA',
    },
  },
  {
    mnemonic: 'STI',
    category: 'Processor Control',
    syntax: ['STI'],
    description: 'Set Interrupt Flag. Enables maskable hardware interrupts (IF = 1).',
    operands: 'IF ← 1',
    opcodeBytes: 'FB',
    instructionSize: '1 byte',
    flagsAffected: ['IF'],
    flagsCleared: [],
    clocksMin: 2,
    clocksMax: 2,
    example: {
      before: 'IF = 0',
      instruction: 'STI',
      after: 'IF = 1 (hardware interrupts enabled)',
      machineCode: 'FB',
    },
  },
];

export function searchInstructions(query: string): InstructionEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return INSTRUCTION_DATABASE;
  return INSTRUCTION_DATABASE.filter(inst =>
    inst.mnemonic.toLowerCase().includes(q) ||
    inst.description.toLowerCase().includes(q) ||
    inst.category.toLowerCase().includes(q)
  );
}

export function getByCategory(category: InstructionCategory): InstructionEntry[] {
  return INSTRUCTION_DATABASE.filter(inst => inst.category === category);
}

export const INSTRUCTION_CATEGORIES: InstructionCategory[] = [
  'Data Transfer',
  'Arithmetic',
  'Logic',
  'Shift & Rotate',
  'Control Transfer',
  'String',
  'Stack',
  'Processor Control',
  'BCD',
];
